trigger:
  - main

pool:
  name: momentic-ubuntu-xl

variables:
  - group: momentic-prod

jobs:
  - job: RunMomentic
    displayName: "Run Momentic"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 20.x
        displayName: "Use Node v20"

      - script: npm install -g yarn && yarn set version berry
        displayName: install and upgrade yarn

      - script: corepack enable
        displayName: "Enable corepack"

      - script: cd yarn-example && yarn install --immutable
        displayName: install dependencies

      - script: cd yarn-example && ls -a
        displayName: "List files in the current directory"

      - script: node --version
        displayName: "Node.js version"

      - script: cd yarn-example && yarn dlx momentic@latest install-browsers chromium
        displayName: "Install Chromium browser via Momentic"

      - script: cd yarn-example && CI=true yarn dlx momentic@latest run --verbose --api-key $(MOMENTIC_API_KEY) random-test.test.yaml
        displayName: Execute test via Momentic
