trigger:
  - main

pool:
  name: momentic-ubuntu-xl

variables:
  - group: momentic-prod

jobs:
  - job: RunMomentic
    displayName: "Run Momentic"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 20.x
        displayName: "Use Node v20"

      # - script: npm install -g yarn && yarn set version berry
      #   displayName: install and upgrade yarn
      - script: npm i -g corepack@latest && corepack enable
        displayName: "Enable corepack"

      - script: npm install -g pnpm@8.7.6 --force
        displayName: "Install pnpm"

      - script: cd yarn-example && pnpm i --frozen-lockfile
        displayName: install dependencies

      - script: cd yarn-example && ls -a
        displayName: "List files in the current directory"

      - script: node --version
        displayName: "Node.js version"

      - script: cd yarn-example && CI=true npx momentic@latest check-config
        env:
          CI: true

      - task: Bash@3
        inputs:
          targetType: "inline"
          script: "cd yarn-example && Date && CI=true npx momentic@alpha --log-level debug run random-test.test.yaml"
        env:
          CI: true
          BASH_ENV: "~/.profile"
