version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:22.12.0

jobs:
  run-tests:
    executor: node
    parallelism: 2
    working_directory: ~/project/single-project
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install app dependencies
          command: npm --prefix ../ ci
      - run:
          name: Install testing dependencies
          command: npm ci
      - run:
          name: Install Browsers
          command: npx momentic install-browsers chromium
      - run:
          name: Run tests
          command: |
            npx momentic run create-react-app-test.test.yaml \
              --start "npm --prefix ../ run start" \
              --output-dir test-results/shard-${CIRCLE_NODE_INDEX} \
              --env development \
              --shard-index $(($CIRCLE_NODE_INDEX+1)) \
              --shard-count ${CIRCLE_NODE_TOTAL}
      - store_artifacts:
          when: always
          path: ./test-results
      - persist_to_workspace:
          when: always
          root: .
          paths:
            - test-results
  upload-results:
    executor: node
    working_directory: ~/project/single-project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - attach_workspace:
          at: .
      - run:
          name: Merge test results
          command: npx momentic results merge --output-dir test-results/merged test-results
      - run:
          name: Upload test results
          command: npx momentic results upload test-results/merged

workflows:
  UI_Tests:
    jobs:
      - run-tests
      - upload-results:
          requires:
            - run-tests
