name: default
include:
  - "**/*.test.yaml"
  - "**/*.module.yaml"
environments:
  - name: development
    baseUrl: https://momentic-github-actions-demo.vercel.app/
    envVariables: {}
  - name: production
    baseUrl: https://gptzero.me
    envVariables: {}
browser:
  # these are optional, see https://momentic.ai/docs/cli/configuration#browser-options
  autoExpandIframes: true
  disableSecondaryCacheResolution: true
  globalLocatorRedirect: true
  visualActions: true
advanced:
  # these are optional, see https://momentic.ai/docs/cli/configuration#advanced-options
  fakerConstantSeed: true
ai:
  # these are optional, see https://momentic.ai/docs/cli/configuration#ai-options
  aiPageFiltering: true
  agentConfig:
    locator: v2
    assertion: v2
gitMainBranch: main
gitProtectedBranches:
  - production
