name: marketing
include:
  - "**/*.test.yaml"
  - "**/*.module.yaml"
  - "../../common/**/*.module.yaml"
ai:
  agentConfig:
    failure-classification: v2
  aiFailureAnalysis: true
  classification: true
  healing:
    onFail: warn
    onSuccess: pull-request
environments:
  - name: test
    baseUrl: https://google.com
    envFile: ../../test.env
    envVariables:
      VAR_FROM_SHELL: ${VAR_FROM_SHELL}
