name: Test multi-project

env:
  MOMENTIC_API_KEY: ${{ secrets.MOMENTIC_API_KEY }}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run all project tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./multi-project-workspace
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install headless browsers for automation
        # Choose which browsers you want to install, see https://momentic.ai/docs/browsers
        run: npx momentic install-browsers chromium
      - name: Run specific marketing tests using project name and substring match
        run: npx momentic run --upload-results --filter marketing variable
        env:
          VAR_FROM_SHELL: test-var-from-shell
      - name: Run all QA tests using explicit config path
        run: npx momentic run --upload-results --config qa/momentic.config.yaml .
      - name: Run dashboard tests using absolute path
        run: |
          cd apps/dashboard
          npx momentic run --upload-results google-search.test.yaml
