name: Test multi-project

env:
  MOMENTIC_API_KEY: ${{ secrets.MOMENTIC_API_KEY }}

on:
  pull_request:

jobs:
  run-tests:
    name: Run all project tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: read
    defaults:
      run:
        working-directory: ./multi-project-workspace-example
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Run specific marketing tests using project name and substring match
        run: npx momentic@^1 run --filter marketing variable
        env:
          VAR_FROM_SHELL: test-var-from-shell
      - name: Run all QA tests using config path
        run: npx momentic@^1 run --config qa/momentic.config.yaml .
      - name: Run dashboard tests using absolute path
        run: |
          cd apps/dashboard
          npx momentic@^1 run google-search.test.yaml