name: Test PR

env:
  MOMENTIC_API_KEY: ${{ secrets.MOMENTIC_API_KEY }}

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./single-project
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install headless browsers for automation
        # Choose which browsers you want to install, see https://momentic.ai/docs/browsers
        run: npx momentic install-browsers chromium
      - name: Run tests and write outputs locally
        run: npx momentic run --output-dir test-results/results-with-inputs --input-csv data/inputs.csv input-from-csv-test.test.yaml
      - name: Upload results to Momentic Cloud for easy viewing
        run: npx momentic results upload test-results/results-with-inputs
        if: always()
